// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transaction_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_TransactionModel _$TransactionModelFromJson(Map<String, dynamic> json) =>
    _TransactionModel(
      id: json['id'] as String,
      amount: (json['amount'] as num).toDouble(),
      type: $enumDecode(_$TransactionTypeEnumMap, json['type']),
      category: json['category'] as String,
      description: json['description'] as String? ?? '',
      date: const TimestampConverter().fromJson(json['date'] as Timestamp),
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      receiptUrl: json['receiptUrl'] as String?,
    );

Map<String, dynamic> _$TransactionModelToJson(_TransactionModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'amount': instance.amount,
      'type': _$TransactionTypeEnumMap[instance.type]!,
      'category': instance.category,
      'description': instance.description,
      'date': const TimestampConverter().toJson(instance.date),
      'isAutoGenerated': instance.isAutoGenerated,
      'receiptUrl': instance.receiptUrl,
    };

const _$TransactionTypeEnumMap = {
  TransactionType.expense: 'EXPENSE',
  TransactionType.income: 'INCOME',
};
